apiVersion: apps/v1
kind: Deployment
metadata:
  name: notifications-service-app
spec:
  selector:
    matchLabels:
      app: notifications-service-app
  template:
    metadata:
      labels:
        app: notifications-service-app
    spec:
      containers:
        - name: notifications-service-app
          image: IMAGE_URL:TAG
          imagePullPolicy: Always
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
          ports:
            - containerPort: 8088
          env:
            - name: EUREKA_SERVER_URL
              valueFrom:
                configMapKeyRef:
                  key: eureka_server_url
                  name: eureka-cm
            - name: CONFIG_SERVER_URL
              valueFrom:
                configMapKeyRef:
                  key: config_server_url
                  name: config-cm
            - name: MONGODB_URL
              valueFrom:
                configMapKeyRef:
                  key: mongo_url
                  name: mongo-cm
            - name: KAFKA_URL
              valueFrom:
                configMapKeyRef:
                  key: kafka_url
                  name: kafka-cm

---
apiVersion: v1
kind: Service
metadata:
  name: notifications-service-svc
spec:
  selector:
    app: notifications-service-app
  ports:
    - port: 80
      targetPort: 8088